name: CI

on:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Rubberduck (Excel Add-in + CLI)
        shell: pwsh
        run: |
          choco install rubberduck -y

      - name: Locate Rubberduck CLI and Run Tests
        shell: pwsh
        run: |
          cd workbook

          # Try locating CLI via Get-Command
          $cli = (Get-Command Rubberduck.CLI.exe -ErrorAction SilentlyContinue).Source

          # Fallback if not in PATH
          if (-not $cli -or -not (Test-Path $cli)) {
            $cli = "C:\Program Files\Rubberduck\Rubberduck.CLI.exe"
          }

          if (-not (Test-Path $cli)) {
            Write-Error "Rubberduck CLI not found at $cli"
            exit 1
          }

          Write-Host "Rubberduck CLI found at $cli"
          & $cli -project ETL_Accelerator.xlsm -tests all
