name: CI

on:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download Rubberduck CLI
        shell: pwsh
        run: |
          $releaseUrl = "https://github.com/rubberduck-vba/Rubberduck/releases/download/v2.5.91/RubberduckCLI.zip"
          $zipPath = "$env:RUNNER_TEMP\\rubberduck-cli.zip"
          $extractPath = "$env:RUNNER_TEMP\\rubberduck"

          Invoke-WebRequest -Uri $releaseUrl -OutFile $zipPath
          Expand-Archive -Path $zipPath -DestinationPath $extractPath

          # Save the CLI path to the environment for later steps
          echo "CLI_PATH=$extractPath\\Rubberduck.CLI.exe" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append

      - name: Run VBA Tests
        shell: pwsh
        run: |
          cd workbook
          & $env:CLI_PATH -project ETL_Accelerator.xlsm -tests all
