name: CI

on:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Rubberduck (Excel Add-in + CLI)
        shell: pwsh
        run: |
          choco install rubberduck -y

      - name: Locate Rubberduck CLI and Run Tests
        shell: pwsh
        run: |
          cd workbook
        
          # Try finding Rubberduck.CLI.exe anywhere on disk
          $cli = Get-ChildItem -Path 'C:\' -Filter 'Rubberduck.CLI.exe' -Recurse -ErrorAction SilentlyContinue -Force |
                 Select-Object -First 1 -ExpandProperty FullName
        
          if (-not $cli -or -not (Test-Path $cli)) {
            Write-Error "Rubberduck CLI not found on any drive"
            exit 1
          }
        
          Write-Host "Rubberduck CLI found at: $cli"
          & $cli -project ETL_Accelerator.xlsm -tests all
        
