name: CI

on:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Rubberduck CLI
        shell: pwsh
        run: |
          choco install rubberduck-cli -y

      - name: Find Rubberduck CLI and Run Tests
        shell: pwsh
        run: |
          cd workbook

          # Try resolving CLI from system PATH
          $cli = (Get-Command Rubberduck.CLI.exe -ErrorAction SilentlyContinue).Source

          # Fallback to known Chocolatey install path
          if (-not $cli -or -not (Test-Path $cli)) {
            $cli = 'C:\ProgramData\chocolatey\bin\Rubberduck.CLI.exe'
          }

          # Fail if still not found
          if (-not (Test-Path $cli)) {
            Write-Error \"Rubberduck CLI not found. Checked PATH and fallback.\"
            exit 1
          }

          Write-Host \"Rubberduck CLI found at: $cli\"
          & $cli -project ETL_Accelerator.xlsm -tests all
