name: CI
on:
  push:
    branches: [ main ]
jobs:
  test:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Rubberduck via Chocolatey
        shell: pwsh
        run: |
          choco install rubberduck -y

      - name: Run VBA Tests
        shell: pwsh
        run: |
          cd workbook
          # Assume Rubberduck CLI is in the Program Files directory
          $rubberduckPath = "C:\Program Files\Rubberduck\Rubberduck.CLI.exe"

          if (Test-Path $rubberduckPath) {
            Write-Host "Attempting to run Rubberduck CLI from: $rubberduckPath"
            & $rubberduckPath -project ETL_Accelerator.xlsm -tests all
          } else {
            Write-Error "Rubberduck CLI executable not found at assumed path: $rubberduckPath."
            exit 1
          }
