name: CI
on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: windows-latest
    steps:

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Rubberduck via Chocolatey
        shell: pwsh
        run: |
          choco install rubberduck -y

      - name: Check for VBA modules
        shell: pwsh
        id: vba_check
        run: |
          # Launch Excel via COM and count VB components
          $excel = New-Object -ComObject Excel.Application
          $wbPath = "${{ github.workspace }}\workbook\ETL_Accelerator.xlsm"
          $wb = $excel.Workbooks.Open($wbPath, 3)
          $hasCode = $wb.VBProject.VBComponents.Count -gt 0
          $wb.Close($false)
          $excel.Quit()
          Write-Output "hasModules=$hasCode" | Out-File -FilePath $GITHUB_OUTPUT -Encoding UTF8

      - name: Inspect & Run VBA Tests
        if: steps.vba_check.outputs.hasModules == 'true'
        shell: pwsh
        run: |
          Write-Host "✅ VBA code found – running Rubberduck CLI"
          & Rubberduck.CLI.exe inspect `
              --project "$env:GITHUB_WORKSPACE\workbook\ETL_Accelerator.xlsm" `
              --tests all

      - name: Skip Rubberduck (no VBA)
        if: steps.vba_check.outputs.hasModules != 'true'
        shell: pwsh
        run: |
          Write-Host "ℹ️  No VBA modules detected; skipping Rubberduck CLI."
