name: CI
on:
  push:
    branches: [ main ]
jobs:
  test:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Rubberduck via Chocolatey
        shell: pwsh
        run: |
          choco install rubberduck -y

      - name: Run VBA Tests
        shell: pwsh
        run: |
          cd workbook
          # Locate Rubberduck CLI executable within the reported installation path
          $rubberduckPath = Get-ChildItem -Path "C:\ProgramData\Rubberduck\" -Filter "Rubberduck.CLI.exe" -ErrorAction SilentlyContinue | Select-Object -ExpandProperty FullName
          
          if ($null -ne $rubberduckPath) {
            Write-Host "Rubberduck CLI found at: $rubberduckPath"
            & $rubberduckPath -project ETL_Accelerator.xlsm -tests all
          } else {
            Write-Error "Rubberduck CLI executable not found at 'C:\ProgramData\Rubberduck\' or its immediate subdirectories. Listing contents for further diagnosis."
            # List immediate contents of C:\ProgramData\Rubberduck\ to further diagnose
            Write-Host "Direct contents of C:\ProgramData\Rubberduck\:"
            Get-ChildItem -Path "C:\ProgramData\Rubberduck\" -ErrorAction SilentlyContinue | Select-Object -ExpandProperty FullName
            exit 1
          }
