name: CI
on:
  push:
    branches: [ main ]
jobs:
  test:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Rubberduck via Chocolatey
        shell: pwsh
        run: |
          choco install rubberduck -y
          # Verify installation
          if (Test-Path "C:\Program Files\Rubberduck\Rubberduck.CLI.exe") {
            Write-Host "Rubberduck CLI found at expected location"
          } else {
            Write-Host "Rubberduck CLI not found at expected location"
            Get-ChildItem "C:\Program Files\Rubberduck" -Recurse | Select-Object FullName
            exit 1
          }

      - name: Run VBA Tests
        shell: pwsh
        run: |
          cd workbook
          # Use PowerShell call operator to launch the CLI
          $rubberduckPath = "C:\ProgramData\Rubberduck\Rubberduck.CLI.exe"
          if (Test-Path $rubberduckPath) {
            & $rubberduckPath -project ETL_Accelerator.xlsm -tests all
          } else {
            Write-Error "Rubberduck CLI not found at: $rubberduckPath"
            exit 1
          }
